[package]
name = "web-crawler"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
anyhow = { version = "1.0", default-features = false }
log = "0.4.27"
env_logger = "0.11.8"
reqwest = { version = "0.12.15", features = ["json"] }
html_parser = "0.7.0"
